#!/usr/bin/env bash
# A Bash script that generates a MySQL dump and creates a compressed archive out of it.

name=$(date '+%d-%m-%Y')
sudo mysqldump -uroot -p"$1" --all-databases | sudo tee backup.sql > /dev/null
tar -zcvf "$name.tar.gz" backup.sql