#!/usr/bin/env bash
# Configure Nginx to run and listen on all the server's active IPv4 IPs

sudo sed -i 's/8080 default_server/80 default_server/g' /etc/nginx/sites-enabled/default
sudo service nginx restart
